// This file is generated by Sapper — do not edit it!
import root from "../routes/_layout.html";
import error from "../routes/_error.html";

const d = decodeURIComponent;

const index = {
	js: () => import("../routes/index.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:index.html__"
};
const about = {
	js: () => import("../routes/about.html"),
	css: "__SAPPER_CSS_PLACEHOLDER:about.html__"
};
const item_$id = {
	js: () => import("../routes/item/[id].html"),
	css: "__SAPPER_CSS_PLACEHOLDER:item/[id].html__"
};
const user_$name = {
	js: () => import("../routes/user/[name].html"),
	css: "__SAPPER_CSS_PLACEHOLDER:user/[name].html__"
};
const $list$93_$91page = {
	js: () => import("../routes/[list]/[page].html"),
	css: "__SAPPER_CSS_PLACEHOLDER:[list]/[page].html__"
};

export const manifest = {
	ignore: [/^\/rss$/, /^\/([^\/]+?)\/rss$/],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ component: index }
			]
		},

		{
			// about.html
			pattern: /^\/about\/?$/,
			parts: [
				{ component: about }
			]
		},

		{
			// item/[id].html
			pattern: /^\/item\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ component: item_$id, params: match => ({ id: d(match[1]) }) }
			]
		},

		{
			// user/[name].html
			pattern: /^\/user\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ component: user_$name, params: match => ({ name: d(match[1]) }) }
			]
		},

		{
			// [list]/[page].html
			pattern: /^\/([^\/]+?)\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ component: $list$93_$91page, params: match => ({ list: d(match[1]), page: d(match[2]) }) }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};

import("/Users/208311/Development/SVELTE/sapper-hacker-news/node_modules/sapper/sapper-dev-client.js").then(client => {
	client.connect(10000);
});