// This file is generated by Sapper — do not edit it!
export const timestamp = 1537756762456;

export const files = [
	"favicon.png",
	"manifest.json",
	"svelte-192.png",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];
export { files as assets }; // legacy

export const shell = [
	"client/client.76b079e8.js",
	"client/chunk.4a882ab2.js",
	"client/index.d17d92e2.js",
	"client/about.5658d486.js",
	"client/[id].bdf2de6b.js",
	"client/[name].529e7b93.js",
	"client/[page].7288749b.js",
	"client/sapper-dev-client.c1ed07a9.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/about\/?$/ },
	{ pattern: /^\/item\/([^\/]+?)\/?$/ },
	{ pattern: /^\/user\/([^\/]+?)\/?$/ },
	{ pattern: /^\/([^\/]+?)\/([^\/]+?)\/?$/ }
];