// This file is generated by Sapper — do not edit it!
import * as route_rss from "../routes/rss.js";
import * as route_$list_rss from "../routes/[list]/rss.js";
import index from "../routes/index.html";
import about from "../routes/about.html";
import item_$id from "../routes/item/[id].html";
import user_$name from "../routes/user/[name].html";
import $list$93_$91page from "../routes/[list]/[page].html";
import root from "../routes/_layout.html";
import error from "../routes/_error.html";

const d = decodeURIComponent;

export const manifest = {
	server_routes: [
		{
			// rss.js
			pattern: /^\/rss$/,
			handlers: route_rss,
			params: () => ({})
		},

		{
			// [list]/rss.js
			pattern: /^\/([^\/]+?)\/rss$/,
			handlers: route_$list_rss,
			params: match => ({ list: d(match[1]) })
		}
	],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ name: "index", file: "index.html", component: index }
			]
		},

		{
			// about.html
			pattern: /^\/about\/?$/,
			parts: [
				{ name: "about", file: "about.html", component: about }
			]
		},

		{
			// item/[id].html
			pattern: /^\/item\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ name: "item_$id", file: "item/[id].html", component: item_$id, params: match => ({ id: d(match[1]) }) }
			]
		},

		{
			// user/[name].html
			pattern: /^\/user\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ name: "user_$name", file: "user/[name].html", component: user_$name, params: match => ({ name: d(match[1]) }) }
			]
		},

		{
			// [list]/[page].html
			pattern: /^\/([^\/]+?)\/([^\/]+?)\/?$/,
			parts: [
				null,
				{ name: "$list$93_$91page", file: "[list]/[page].html", component: $list$93_$91page, params: match => ({ list: d(match[1]), page: d(match[2]) }) }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};