// This file is generated by Sapper — do not edit it!
export const timestamp = 1520084162057;

export const assets = [
	"favicon.png",
	"manifest.json",
	"svelte-192.png",
	"svelte-logo-192.png",
	"svelte-logo-512.png"
];

export const shell = [
	"/client/735f6cbccf7c8144c4e2/item_$id$.0.js",
	"/client/735f6cbccf7c8144c4e2/$list$_$page$.1.js",
	"/client/735f6cbccf7c8144c4e2/user_$name$.2.js",
	"/client/735f6cbccf7c8144c4e2/about.3.js",
	"/client/735f6cbccf7c8144c4e2/_5xx.4.js",
	"/client/735f6cbccf7c8144c4e2/_4xx.5.js",
	"/client/735f6cbccf7c8144c4e2/main.js"
];

export const routes = [
	{ pattern: /^\/about\/?$/ },
	{ pattern: /^\/item(?:\/([^\/]+?))?\/?$/ },
	{ pattern: /^\/user(?:\/([^\/]+?))?\/?$/ },
	{ pattern: /^(?:\/([^\/]+?)(?:\/([^\/]+?))?)?\/?$/ }
];