// This file is generated by Sapper — do not edit it!
import * as _ from '../../routes/index.js';
import about from '../../routes/about.html';
import item_$id$ from '../../routes/item/[id].html';
import user_$name$ from '../../routes/user/[name].html';
import _4xx from '../../routes/4xx.html';
import _5xx from '../../routes/5xx.html';
import $list$_$page$ from '../../routes/[list]/[page].html';

export const routes = [
	{ id: '_', type: 'route', pattern: /^\/?$/, params: () => ({}), module: _ },
	{ id: 'about', type: 'page', pattern: /^\/about\/?$/, params: () => ({}), module: about },
	{ id: 'item_$id$', type: 'page', pattern: /^\/item(?:\/([^\/]+?))?\/?$/, params: match => ({ id: match[1] }), module: item_$id$ },
	{ id: 'user_$name$', type: 'page', pattern: /^\/user(?:\/([^\/]+?))?\/?$/, params: match => ({ name: match[1] }), module: user_$name$ },
	{ error: '4xx', module: _4xx },
	{ error: '5xx', module: _5xx },
	{ id: '$list$_$page$', type: 'page', pattern: /^(?:\/([^\/]+?)(?:\/([^\/]+?))?)?\/?$/, params: match => ({ list: match[1], page: match[2] }), module: $list$_$page$ }
];